[
build
]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[
deploy
]
startCommand = "npm run start:server"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"